name: "Deploy to AWS"

on:
  workflow_run:
    workflows: ["01 Build and Deploy Site"]
    types:
      - completed
  workflow_dispatch:

jobs:
  full-build:
    name: "Deploy to AWS"
    if: ${{ secrets.AWS_S3_BUCKET != "" }} # skip when we don't have this set up 
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout folder"
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: 'test-lesson'

      - name: "Deploy to Bucket"
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'test-lesson'
          DEST_DIR: 'zkamvar-test-lesson'
